### ISSUE TITLE
Android - getLatestVersion returns full stop i.e `.`

### ISSUE THREAD

**Issue by vrautgit** [kimxogus/react-native-version-check#114]
Hello, Thank you for the amazing library.

I am facing one minor issue with the **getLatestVersion** function.
When I am trying to get a version in response I am getting a full stop i.e **.**

Here is my code:
`VersionCheck.getLatestVersion().then((latestVersion) => {`
`  console.log({ latestVersion });`
`})`

In response I am getting this:
[<img width="187" alt="Screenshot 2020-05-20 at 1 31 03 PM" src="https://user-images.githubusercontent.com/22424365/82421633-e70b2900-9a9e-11ea-806b-24d928b01b78.png">](url)

Thanks in advance for the solution.

**Comment by vrautgit** [comment]
The issue is resolved when I updated from version **3.4.0** version to **3.4.1** version

**Comment by jenskuhrjorgensen** [comment]
I'm still experiencing this with version 3.4.1. :(

**Comment by Jeevan-Kishore** [comment]
The issue exists with version `3.4.1`

**Comment by ramyyahari** [comment]
We're still seeing this issue as well, looks like play store might've changed their response.

**Comment by zapcriativo** [comment]
Same problem in version 3.4.2 

    "react-native-version-check": "^3.4.2",
    "react-native-version-check-expo": "^3.4.2",
